### ISSUE TITLE
QQmlApplicationEngine failed to load component

### ISSUE THREAD

**Issue by nscott32** [Kakadu/QOcamlBrowser_quick#2]
Hello,

after running configure && make I have those error:

QQmlApplicationEngine failed to load component
qrc:///ui/Root.qml:3 module "QtQuick.Layouts" is not installed
qrc:///ui/Root.qml:2 module "QtQuick.Controls" is not installed
qrc:///ui/Root.qml:3 module "QtQuick.Layouts" is not installed
qrc:///ui/Root.qml:2 module "QtQuick.Controls" is not installed

ASSERT failure in Creating C++ runtime: "Your QML file seems buggy", file startup_stubs.c, line 134
[1]    17072 abort (core dumped)  ./program.native

**Comment by Kakadu** [comment]
This controls are in the special [Qt modules](http://doc.qt.io/qt-5/qtmodules.html) which could be skipped during installation. In Debian and derivatives they are in separate packages. I need more information about your installation to fix this.

**Comment by nscott32** [comment]
I run archlinux, updated with qt5 updated to last version.

Output of yaourt query about installed package containing the string "qt": 

extra/qt5-base 5.5.1-9 (qt qt5)
    A cross-platform application and UI framework
extra/qt5-declarative 5.5.1-9 (qt qt5)
    Classes for QML and JavaScript languages
extra/qt5-location 5.5.1-9 (qt qt5)
    Provides access to position, satellite and area monitoring classes
extra/qt5-sensors 5.5.1-9 (qt qt5)
    Provides access to sensor hardware and motion gesture recognition
extra/qt5-svg 5.5.1-9 (qt qt5)
    Classes for displaying the contents of SVG files
extra/qt5-tools 5.5.1-9 (qt qt5)
    A cross-platform application and UI framework (Development Tools, QtHelp)
extra/qt5-translations 5.5.1-9 (qt qt5)
    A cross-platform application and UI framework (Translations)
extra/qt5-webchannel 5.5.1-9 (qt qt5)
    Provides access to QObject or QML objects from HTML clients for seamless integration of Qt applications with HTML/JavaScript clients
extra/qt5-webkit 5.5.1-9 (qt qt5)
    Classes for a WebKit2 based implementation and a new QML API
extra/qt5-x11extras 5.5.1-9 (qt qt5)
    Provides platform-specific APIs for X11
extra/qt5-xmlpatterns 5.5.1-9 (qt qt5)
    Support for XPath, XQuery, XSLT and XML schema validation

**Comment by Kakadu** [comment]
https://www.archlinux.org/packages/extra/x86_64/qt5-quickcontrols/files/

**Comment by nscott32** [comment]
Sorry for haven't look up before, in the future I would check packages content before asking.
Thank you !
